### ISSUE TITLE
Fails on nRF52840-DK

### ISSUE THREAD

**Issue by franslundberg** [sAlexander/nrf52-minimal-c#1]
On the dev board nRF52840-DK, the LED1 define should be: `#define LED_1 13`.

**Comment by sAlexander** [comment]
Thanks for the heads up! These values are known to vary between development boards. I submitted the following change to make the LED_1 value default to 13. https://github.com/sAlexander/nrf52-minimal-c/commit/00e270ce052755f46b756dde0efbb30f67650784
